import Collapsible from 'react-collapsible';

export default function SortAndFilters() {
    return (
        <Collapsible trigger={'Additionally...'}>
            <div>
                <div>
                    <h3>Sort</h3>
                    <ul>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="sortBy"
                                    value="name"
                                />
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="sortBy"
                                    value="date"
                                />
                            </label>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="sortOrder"
                                    value="asc"
                                />
                            </label>
                        </li>
                        <li>
                            <label>
                                <input
                                    type="radio"
                                    name="sortOrder"
                                    value="desc"
                                />
                            </label>
                        </li>
                    </ul>
                </div>
                <div>
                    <h3>Filter</h3>
                    <div>
                        <h3>By CompleteTo Date</h3>
                        <ul>
                            <li>
                                <label>
                                    <input
                                        type="radio"
                                        name="filterByDate"
                                        value="desc"
                                    />
                                </label>
                            </li>
                            <li>
                                <label>
                                    <input
                                        type="radio"
                                        name="filterByDate"
                                        value="desc"
                                    />
                                </label>
                            </li>
                            <li>
                                <label>
                                    <input
                                        type="radio"
                                        name="filterByDate"
                                        value="desc"
                                    />
                                </label>
                            </li>
                        </ul>
                        <h3>By Is Completed</h3>
                        <ul>
                            <li>
                                <label>
                                    <input
                                        type="radio"
                                        name="filterByDate"
                                        value="desc"
                                    />
                                </label>
                            </li>
                            <li>
                                <label>
                                    <input
                                        type="radio"
                                        name="filterByDate"
                                        value="desc"
                                    />
                                </label>
                            </li>
                            <li>
                                <label>
                                    <input
                                        type="radio"
                                        name="filterByDate"
                                        value="desc"
                                    />
                                </label>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </Collapsible>
    );
}
